/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlbumSection: typeof import('./src/components/AlbumSection.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    CourseMeetSection: typeof import('./src/components/CourseMeetSection.vue')['default']
    FreeVideoSection: typeof import('./src/components/FreeVideoSection.vue')['default']
    KaraokeSection: typeof import('./src/components/KaraokeSection.vue')['default']
    MediaCarousel: typeof import('./src/components/MediaCarousel.vue')['default']
    MerchandiseSection: typeof import('./src/components/MerchandiseSection.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./src/components/Snackbar.vue')['default']
    SubscriptionDialog: typeof import('./src/components/SubscriptionDialog.vue')['default']
  }
}
